const vintageItems = [
  {
    id: 1,
    title: 'Messing tafellamp uit de jaren 70',
    category: 'interieur',
    categoryLabel: 'Interieur',
    price: 85,
    seller: 'Studio Second Story',
    period: 'Jaren 70',
    condition: 'Goede vintage staat',
    image: 'images/items/messing-tafellamp.jpg',
    description:
      'Een sfeervolle messing tafellamp met een warme, tijdloze uitstraling.',
  },
  {
    id: 2,
    title: 'Donkerbruine leren jas',
    category: 'mode',
    categoryLabel: 'Mode',
    price: 120,
    seller: 'The Archive Closet',
    period: 'Jaren 80',
    condition: 'Goede vintage staat',
    image: 'images/items/donkerbruine-leren-jas.jpg',
    description:
      'Een leren jas met een klassieke snit en lichte gebruikssporen.',
  },
  {
    id: 3,
    title: 'Handgemaakte keramieken vaas',
    category: 'wonen',
    categoryLabel: 'Wonen',
    price: 45,
    seller: 'Object Stories',
    period: 'Jaren 60',
    condition: 'Zeer goede vintage staat',
    image: 'images/items/keramieken-vaas.jpg',
    description:
      'Een organisch gevormde vaas, handgemaakt en afgewerkt met een zachte glazuurlaag.',
  },
  {
    id: 4,
    title: 'Massief houten eetkamerstoel',
    category: 'interieur',
    categoryLabel: 'Interieur',
    price: 65,
    seller: 'Studio Second Story',
    period: 'Jaren 70',
    condition: 'Goede vintage staat',
    image: 'images/items/houten-eetkamerstoel.jpg',
    description:
      'Een stevige houten eetkamerstoel met een eenvoudige, tijdloze vorm.',
  },
  {
    id: 5,
    title: 'Crèmekleurige zijden blouse',
    category: 'mode',
    categoryLabel: 'Mode',
    price: 55,
    seller: 'The Archive Closet',
    period: 'Jaren 90',
    condition: 'Zeer goede vintage staat',
    image: 'images/items/zijden-blouse.jpg',
    description:
      'Een lichte zijden blouse die zowel casual als formeel gedragen kan worden.',
  },
  {
    id: 6,
    title: 'Ovale spiegel met houten rand',
    category: 'wonen',
    categoryLabel: 'Wonen',
    price: 90,
    seller: 'Object Stories',
    period: 'Jaren 70',
    condition: 'Goede vintage staat',
    image: 'images/items/ovale-spiegel.jpg',
    description: 'Een ovale wandspiegel met een warme houten omlijsting.',
  },
];
